#include "DjiActionCamera.h"
DjiActionCamera* DjiActionCamera::instance=nullptr;
static const NimBLEUUID DJI_SERVICE("0000fff0-0000-1000-8000-00805f9b34fb");
static const NimBLEUUID DJI_NOTIFY("0000fff4-0000-1000-8000-00805f9b34fb");
static const NimBLEUUID DJI_WRITE("0000fff5-0000-1000-8000-00805f9b34fb");
DjiActionCamera::DjiActionCamera():callbacks(this){instance=this;}
void DjiActionCamera::begin(){NimBLEDevice::init("FPVCineCam32");NimBLEDevice::setPower(3);NimBLEDevice::setSecurityAuth(true,false,false);NimBLEDevice::setSecurityIOCap(BLE_HS_IO_NO_INPUT_OUTPUT);camState.status="DJI IDLE";camState.model="DJI Action (R SDK transport)";}
bool DjiActionCamera::startScan(String& j){auto* s=NimBLEDevice::getScan();s->setActiveScan(true);s->setInterval(60);s->setWindow(60);auto r=s->getResults(3500,false);j="[";bool first=true;for(int i=0;i<r.getCount();i++){auto* d=r.getDevice(i);if(!d->isAdvertisingService(DJI_SERVICE))continue;if(!first)j+=',';first=false;String n=d->getName().c_str(),a=d->getAddress().toString().c_str();j+="{\"name\":\""+n+"\",\"address\":\""+a+"\",\"type\":"+String(d->getAddress().getType())+"}";}j+="]";s->clearResults();return true;}
bool DjiActionCamera::connectTo(const String&a,uint8_t t){if(!a.length())return false;requestedAddress=a;requestedAddressType=t;connectRequested=true;camState.status="DJI CONNECT QUEUED";return true;}
void DjiActionCamera::connectTaskThunk(void* a){auto*self=(DjiActionCamera*)a;String x=self->requestedAddress;uint8_t t=self->requestedAddressType;self->connectRequested=false;self->performConnect(x,t);self->connectTaskRunning=false;vTaskDelete(nullptr);}
void DjiActionCamera::performConnect(const String&a,uint8_t t){if(client&&client->isConnected())client->disconnect();notifyChar=writeChar=nullptr;camState.connected=false;camState.controlReady=false;camState.status="DJI CONNECTING";if(!client){client=NimBLEDevice::createClient();client->setClientCallbacks(&callbacks,false);client->setConnectTimeout(8000);}NimBLEAddress ad(a.c_str(),t);if(!client->connect(ad,true,false,false)){camState.status="DJI CONNECT FAIL";return;}auto* svc=client->getService(DJI_SERVICE);if(!svc){camState.status="NO DJI RSDK SERVICE";client->disconnect();return;}notifyChar=svc->getCharacteristic(DJI_NOTIFY);writeChar=svc->getCharacteristic(DJI_WRITE);bool n=false;if(notifyChar){if(notifyChar->canNotify())n=notifyChar->subscribe(true,notifyCb);else if(notifyChar->canIndicate())n=notifyChar->subscribe(false,notifyCb);}camState.connected=true;camState.paired=true;camState.telemetryReady=n;camState.controlReady=false;camState.status=(writeChar&&notifyChar)?"DJI RSDK LINK - AUTH PENDING":"DJI RSDK CHAR MISSING";}
bool DjiActionCamera::setRecording(bool on){camState.lastCommand=on?"REC":"STOP";camState.lastWrite="DJI RSDK AUTH/COMMAND PENDING";camState.status="DJI RSDK CONTROL NOT YET ENABLED";return false;}
void DjiActionCamera::notifyCb(NimBLERemoteCharacteristic*,uint8_t* d,size_t l,bool){if(!instance)return;instance->camState.telemetryReady=true;char b[48]={};size_t p=0;for(size_t i=0;i<l&&i<12&&p+3<sizeof(b);i++)p+=snprintf(b+p,sizeof(b)-p,"%s%02X",i?" ":"",d[i]);instance->camState.lastIncoming=String(b);}
void DjiActionCamera::loop(){if(connectRequested&&!connectTaskRunning){connectTaskRunning=true;if(xTaskCreate(connectTaskThunk,"dji-connect",6144,this,1,nullptr)!=pdPASS){connectTaskRunning=false;connectRequested=false;camState.status="CONNECT TASK FAIL";}}if(reconnectWanted&&!connectTaskRunning&&!connectRequested&&millis()>=nextReconnectMs&&savedAddress.length()){reconnectWanted=false;connectTo(savedAddress,savedAddressType);}}
void DjiActionCamera::disconnect(){if(client&&client->isConnected())client->disconnect();}
void DjiActionCamera::forgetPairing(){disconnect();NimBLEDevice::deleteAllBonds();savedAddress="";camState=CameraState{};camState.status="DJI PAIRING CLEARED";}
void DjiActionCamera::ClientCallbacks::onConnect(NimBLEClient*){o->camState.connected=true;o->camState.status="DJI LINK UP";}
void DjiActionCamera::ClientCallbacks::onDisconnect(NimBLEClient*,int r){o->camState.connected=false;o->camState.controlReady=false;o->camState.telemetryReady=false;o->camState.status="DJI OFFLINE ("+String(r)+")";if(o->savedAddress.length()){o->reconnectWanted=true;o->nextReconnectMs=millis()+2500;}}
